spring:
  application:
    name: pgNosqlDemo
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.25.31:5432/postgres
      username: postgres
      password: wt_ocean
      hikari:
        connection-timeout: 30000
        maximum-pool-size: 20
        #   连接池名
        pool-name: Hikari-pgSql-pool-1
        #最小空闲连接数
        minimum-idle: 5
    secondary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.29.129:3306/testdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: wt_ocean
      hikari:
        #连接池名
        pool-name: Hikari-mySql-pool-1
        #最小空闲连接数
        minimum-idle: 5
        # 空闲连接存活最大时间，默认10分钟
        idle-timeout: 600000
        # 连接池最大连接数，默认是10
        maximum-pool-size: 10
        # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        max-lifetime: 1800000
        # 数据库连接超时时间,默认30秒
        connection-timeout: 30000
        # 连接测试query
        connection-test-query: SELECT 1
  jackson:
    time-zone: GMT+8
  jpa:
    open-in-view: true
    show_sql: true
    properties:
      hibernate:
#       hbm2ddl 生效级别更高
        ddl-auto: none
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update